// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Creuna.Basis.Revisited.Web")]
[assembly: AssemblyProductAttribute("Creuna.Basis.Revisited.Web")]
[assembly: AssemblyDescriptionAttribute("A slim template for new Episerver projects")]
[assembly: AssemblyVersionAttribute("0.1")]
[assembly: AssemblyFileVersionAttribute("0.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Creuna.Basis.Revisited.Web";
        internal const System.String AssemblyProduct = "Creuna.Basis.Revisited.Web";
        internal const System.String AssemblyDescription = "A slim template for new Episerver projects";
        internal const System.String AssemblyVersion = "0.1";
        internal const System.String AssemblyFileVersion = "0.1";
    }
}
