// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Episerver Basis Slim Scaffolder")>]
[<assembly: AssemblyVersionAttribute("1.2.1.2")>]
[<assembly: AssemblyDescriptionAttribute("Use this to scaffold a solution in the working directory. Will optionally take an argument that specifies the directory to scaffold to.")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Episerver Basis Slim Scaffolder"
    let [<Literal>] AssemblyVersion = "1.2.1.2"
    let [<Literal>] AssemblyDescription = "Use this to scaffold a solution in the working directory. Will optionally take an argument that specifies the directory to scaffold to."
